### ISSUE TITLE
mascot does not compile

### ISSUE THREAD

**Issue by aydindemircioglu** [Joyeewen/mascot_svm#1]
current mascot does not seem to compile. there are several errors--
initially i get

```
$ make
/usr/local/cuda/bin/nvcc -O2 -arch=sm_20 -lrt -o classificationKernel_cu.o -c src/classificationKernel.cu
In file included from src/classificationKernel.cu:2:0:
src/classificationKernel.h:13:32: fatal error: gpu_global_utility.h: No such file or directory
compilation terminated.
Makefile:19: recipe for target 'classificationKernel_cu.o' failed
make: *** [classificationKernel_cu.o] Error 1
```

when i fix the path, i get "deviceHessian unknown". this i can fix by changing the IFDEF in deviceHessian.h. but then i get gnNumOfThreads not known. i can fix this by removing it by setting it to 8. then i still get path-errors. etc

is the current source code the latest, compiling one?

**Comment by Joyeewen** [comment]
You may try the earlier (the earliest perhaps) versions. I am currently
integrating regression modules to the project, which may cause the compile
failed.

I will fix it as soon as I can. Thanks!
------
Sent from my mobile phone
On Jul 6, 2016 20:44, "aydin demircioglu" <notifications@github.com> wrote:

current mascot does not seem to compile. there are several errors--
initially i get

$ make
/usr/local/cuda/bin/nvcc -O2 -arch=sm_20 -lrt -o
classificationKernel_cu.o -c src/classificationKernel.cu
In file included from src/classificationKernel.cu:2:0:
src/classificationKernel.h:13:32: fatal error: gpu_global_utility.h:
No such file or directory
compilation terminated.
Makefile:19: recipe for target 'classificationKernel_cu.o' failed
make: *** [classificationKernel_cu.o] Error 1

when i fix the path, i get "deviceHessian unknown". this i can fix by
changing the IFDEF in deviceHessian.h. but then i get gnNumOfThreads not
known. i can fix this by removing it by setting it to 8. then i still get
path-errors. etc

is the current source code the latest, compiling one?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Joyeewen/mascot_svm/issues/1>, or mute the thread
<https://github.com/notifications/unsubscribe/AF5aOZFRT5cJpfx2qgHceN6oag5WXRDIks5qS4cYgaJpZM4JF9e->
.

**Comment by aydindemircioglu** [comment]
thanks for the hint, it now compiles. 
can you also specify somewhere the licence for the code, i.e. is it gpl or bsd or ...?

**Comment by Joyeewen** [comment]
No problem. I will specify the licence and fix the issues as soon as I can.

Best wishes
